# Generated by Django 2.2.2 on 2020-04-09 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория товаров')),
            ],
        ),
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Сорт продуктов')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Порода дерева')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('length', models.PositiveIntegerField(verbose_name='Длина')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('rating', models.PositiveIntegerField(verbose_name='Рейтинг продукта')),
                ('date', models.DateField(auto_now=True)),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото продукта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Category', verbose_name='Категория товара')),
                ('sort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Sort', verbose_name='Сорт')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Species', verbose_name='Порода дерева')),
            ],
        ),
    ]
