# Generated by Django 2.2.2 on 2020-04-10 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200410_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Sort', verbose_name='Сорт'),
        ),
    ]
