# Generated by Django 2.2.2 on 2020-04-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200409_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=0, verbose_name='Рейтинг продукта'),
        ),
    ]
