# Generated by Django 2.2.2 on 2020-04-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200410_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Категория товаров'),
        ),
        migrations.AlterField(
            model_name='sort',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Сорт продуктов'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Порода дерева'),
        ),
    ]
