# Generated by Django 2.2.2 on 2020-04-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
