# Generated by Django 2.2.2 on 2020-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20200511_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(default='Самовывоз', max_length=20),
        ),
    ]
